export const GET_COMPETITIONS = 'GET_COMPETITIONS';

export const GET_STANDINGS = 'GET_STANDINGS';
export const CLEAR_STANDINGS = 'CLEAR_STANDINGS';

export const GET_TEAM = 'GET_TEAM';
export const CLEAR_TEAM = 'CLEAR_TEAM';

export const ADD_PLAYER = 'ADD_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';
export const SET_PLAYER_TO_ADD_VALUE = 'SET_PLAYER_TO_ADD_VALUE';
